### PR TITLE
Add detectors/LICENSE

### PR DESCRIPTION
**Pull request by matbryan52**
Adds license file for detectors to Manifest (feel free to delete the PR and commit direct to master!)

### CODE REVIEW

**Comment by sk1p** [comment]
`check_example_notebooks` has an interesting failure:

https://dev.azure.com/LiberTEM/4c010e98-cc2f-429f-a98f-0cc6d3254a52/_apis/build/builds/2296/logs/109

> 2023-05-02T20:44:17.9195837Z Traceback (most recent call last):
> 2023-05-02T20:44:17.9198862Z   File "/azp/agent/_work/2/s/.tox/notebooks/bin/libertem-live-mib-sim", line 8, in <module>
> 2023-05-02T20:44:17.9200234Z     sys.exit(main())
> 2023-05-02T20:44:17.9201978Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
> 2023-05-02T20:44:17.9202894Z     return self.main(*args, **kwargs)
> 2023-05-02T20:44:17.9204885Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/click/core.py", line 1055, in main
> 2023-05-02T20:44:17.9206196Z     rv = self.invoke(ctx)
> 2023-05-02T20:44:17.9208416Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
> 2023-05-02T20:44:17.9209757Z     return ctx.invoke(self.callback, **ctx.params)
> 2023-05-02T20:44:17.9211719Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/click/core.py", line 760, in invoke
> 2023-05-02T20:44:17.9212766Z     return __callback(*args, **kwargs)
> 2023-05-02T20:44:17.9214583Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem_live/detectors/merlin/sim.py", line 832, in main
> 2023-05-02T20:44:17.9215824Z     camera_sim = CameraSim(
> 2023-05-02T20:44:17.9217861Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem_live/detectors/merlin/sim.py", line 714, in __init__
> 2023-05-02T20:44:17.9218987Z     stop_event=self.stop_event, first_frame_headers=self.sim.first_frame_headers,
> 2023-05-02T20:44:17.9223307Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem_live/detectors/merlin/sim.py", line 266, in first_frame_headers
> 2023-05-02T20:44:17.9226491Z     self.open()
> 2023-05-02T20:44:17.9227911Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem_live/detectors/merlin/sim.py", line 383, in open
> 2023-05-02T20:44:17.9228997Z     super().open()
> 2023-05-02T20:44:17.9230499Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem_live/detectors/merlin/sim.py", line 192, in open
> 2023-05-02T20:44:17.9231789Z     self._warmup()
> 2023-05-02T20:44:17.9233528Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem_live/detectors/merlin/sim.py", line 256, in _warmup
> 2023-05-02T20:44:17.9234718Z     slices, ranges, scheme_indices = fileset.get_read_ranges(
> 2023-05-02T20:44:17.9236341Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/libertem/io/dataset/mib.py", line 954, in get_read_ranges
> 2023-05-02T20:44:17.9237661Z     return default_get_read_ranges(**kwargs)
> 2023-05-02T20:44:17.9239511Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
> 2023-05-02T20:44:17.9241398Z     error_rewrite(e, 'typing')
> 2023-05-02T20:44:17.9243073Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 407, in error_rewrite
> 2023-05-02T20:44:17.9244188Z     raise e
> 2023-05-02T20:44:17.9245832Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
> 2023-05-02T20:44:17.9247163Z     return_val = self.compile(tuple(argtypes))
> 2023-05-02T20:44:17.9248794Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 965, in compile
> 2023-05-02T20:44:17.9250098Z     cres = self._compiler.compile(args, return_type)
> 2023-05-02T20:44:17.9251891Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 129, in compile
> 2023-05-02T20:44:17.9253623Z     raise retval
> 2023-05-02T20:44:17.9255351Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
> 2023-05-02T20:44:17.9256553Z     retval = self._compile_core(args, return_type)
> 2023-05-02T20:44:17.9259569Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
> 2023-05-02T20:44:17.9260987Z     cres = compiler.compile_extra(self.targetdescr.typing_context,
> 2023-05-02T20:44:17.9262722Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler.py", line 742, in compile_extra
> 2023-05-02T20:44:17.9263992Z     return pipeline.compile_extra(func)
> 2023-05-02T20:44:17.9266496Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler.py", line 460, in compile_extra
> 2023-05-02T20:44:17.9267962Z     return self._compile_bytecode()
> 2023-05-02T20:44:17.9269686Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler.py", line 528, in _compile_bytecode
> 2023-05-02T20:44:17.9270922Z     return self._compile_core()
> 2023-05-02T20:44:17.9272618Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler.py", line 507, in _compile_core
> 2023-05-02T20:44:17.9273885Z     raise e
> 2023-05-02T20:44:17.9275741Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler.py", line 494, in _compile_core
> 2023-05-02T20:44:17.9277225Z     pm.run(self.state)
> 2023-05-02T20:44:17.9279402Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 368, in run
> 2023-05-02T20:44:17.9280707Z     raise patched_exception
> 2023-05-02T20:44:17.9282521Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
> 2023-05-02T20:44:17.9285582Z     self._runPass(idx, pass_inst, state)
> 2023-05-02T20:44:17.9289905Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
> 2023-05-02T20:44:17.9291241Z     return func(*args, **kwargs)
> 2023-05-02T20:44:17.9293604Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
> 2023-05-02T20:44:17.9294799Z     mutated |= check(pss.run_pass, internal_state)
> 2023-05-02T20:44:17.9296758Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
> 2023-05-02T20:44:17.9297865Z     mangled = func(compiler_state)
> 2023-05-02T20:44:17.9299627Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typed_passes.py", line 110, in run_pass
> 2023-05-02T20:44:17.9300609Z     typemap, return_type, calltypes, errs = type_inference_stage(
> 2023-05-02T20:44:17.9302604Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typed_passes.py", line 86, in type_inference_stage
> 2023-05-02T20:44:17.9303804Z     infer.build_constraint()
> 2023-05-02T20:44:17.9305672Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typeinfer.py", line 1039, in build_constraint
> 2023-05-02T20:44:17.9306663Z     self.constrain_statement(inst)
> 2023-05-02T20:44:17.9308310Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typeinfer.py", line 1386, in constrain_statement
> 2023-05-02T20:44:17.9309262Z     self.typeof_assign(inst)
> 2023-05-02T20:44:17.9310816Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typeinfer.py", line 1461, in typeof_assign
> 2023-05-02T20:44:17.9312084Z     self.typeof_global(inst, inst.target, value)
> 2023-05-02T20:44:17.9313721Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typeinfer.py", line 1561, in typeof_global
> 2023-05-02T20:44:17.9314746Z     typ = self.resolve_value_type(inst, gvar.value)
> 2023-05-02T20:44:17.9316441Z   File "/azp/agent/_work/2/s/.tox/notebooks/lib/python3.9/site-packages/numba/core/typeinfer.py", line 1482, in resolve_value_type
> 2023-05-02T20:44:17.9317325Z     raise TypingError(msg, loc=inst.loc)
> 2023-05-02T20:44:17.9318360Z numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> 2023-05-02T20:44:17.9319746Z NameError: name 'unsafe_empty_inferred' is not defined
> 

I can reproduce this locally, probably it's related to the new `numba` version.

**Comment by sk1p** [comment]
> And it failed to complete I see, the CI run timed out. I will check if I can reproduce also.

Yeah, the CI times out because the simulator doesn't start.  I can reproduce this with `tox -e notebooks -r`.

**Comment by sk1p** [comment]
> Yeah, the CI times out because the simulator doesn't start. I can reproduce this with `tox -e notebooks -r`.

... and with a fresh environment, miniconda, Python 3.9 with just `pip install -e /path/to/libertem-live/ -r test_requirements.txt`, and then running `libertem-live-mib-sim /some/file.hdr` crashes.

**Comment by sk1p** [comment]
Hm, it seems to be an issue around numba caching - for reproduction, it's important to not have old numba cache files around. Best to nuke all `__pycache__` directories in the LiberTEM package (possibly the one in the venv, if you have a non-editable install).

**Comment by sk1p** [comment]
> Hm, it seems to be an issue around numba caching - for reproduction, it's important to not have old numba cache files around. Best to nuke all `__pycache__` directories in the LiberTEM package (possibly the one in the venv, if you have a non-editable install).

It does not seem related to our custom numba caching - when bypassing the `cached_njit` to just use the normal `numba.njit` decorator unchanged, the same error is triggered.

**Comment by sk1p** [comment]
I'm working on a reproducer of the bug - from a first impression, it has to do with `numba.cuda` and closure inlining somehow (even though the failing code does not use CUDA at all - importing `numba.cuda` somewhere before works around the bug!)

**Comment by sk1p** [comment]
Current status:

```python
import numba
import numpy as np

# uncomment one of these lines to work around the problem:
# import numba.np.unsafe.ndarray
# import numba.cuda  # indirectly imports numba.np.unsafe.ndarray

@numba.njit()
def _fn():
    np.array([1 for _ in range(16)])

_fn()
```

**Comment by sk1p** [comment]
Filed as https://github.com/numba/numba/issues/8940

**Comment by matbryan52** [comment]
> Filed as [numba/numba#8940](https://github.com/numba/numba/issues/8940)

Well done for tracking this down, and for merging. Sorry to not reply sooner was away most of yesterday.

I think this was the last item needed to get the conda release to build correctly (I tested it without the license file and all the tests passed) - so if you can cut a new rc then I'll run a final check before pushing to conda-forge.

**Comment by sk1p** [comment]
> I think this was the last item needed to get the conda release to build correctly (I tested it without the license file and all the tests passed) - so if you can cut a new rc then I'll run a final check before pushing to conda-forge.

https://test.pypi.org/project/libertem-live/ v0.2.1rc9 is available. There's still a CI issue - it doesn't automatically trigger for tags or stable branches anymore, and manually running doesn't properly push the artifacts to GitHub. :/

**Pull request merged**
