### PR TITLE
MIB Quad 2x2 RAW support for 1/6/12bit

### LINKED ISSUE #34: Support for raw Merlin quad data
See https://github.com/LiberTEM/LiberTEM/issues/1135 for details!

Since LiberTEM-live has its own reader, we will probably also have to implement the same method here.

### PR DESCRIPTION
**Pull request by sk1p**
Experimental, but tested with simulator. Fixes #34

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-live-data` passed

### CODE REVIEW

**Comment by sk1p** [comment]
Simulator needs changes to be compatible to both LiberTEM 0.8 and newer - I'll push a fix shortly.

**Comment by sk1p** [comment]
We tested this today, at least the 6bit version works very well in practice; performance-wise 1bit mode should be even better (and allows for higher frame rates ⇒ check next time how low of a dwell time we can select)

**Comment by sk1p** [comment]
This should now be ready for review. The decoders now have quite complete and robust test coverage, while the `libertem_live.detectors.merlin.data` module is still lacking in that regard - something to be improved later.

**Comment by sk1p** [comment]
Note that the issue fixed in 80969ad ("Overwrite of parallel loop index") is also [present in the current master branch](https://dev.azure.com/LiberTEM/LiberTEM-live/_build/results?buildId=1547&view=logs&j=41bf2667-f691-51b9-4cd2-a2b5eaccc61b&t=1d52ad30-7055-5883-4708-c018a2bde452) - so we should either a) merge this PR soon, or b) extract the fix and merge that independently. Then we should also soon do a release, to make things work with the current numba version. I propose we do that directly after LiberTEM v0.9 at the latest.

**Review by uellue — APPROVED** [review]
Discussion with @sk1p:

Right now, there is quite some similarity between LiberTEM-live QD Merlin support and LiberTEM MIB support, but they can't be shared easily because of differences in the back-end.

In the future, the I/O code might be reqritten in Rust to reduce the compilation delay during the first run. At that point one could investigate how LiberTEM and LiberTEM-live can share the same low-level decoders for formats that are the same on disk and in a live stream.

LGTM, tested with Oxford, merging!

**Pull request merged**
