### PR TITLE
Re-enable `tox-uv`

### PR DESCRIPTION
**Pull request by sk1p**
Should work now with hatch.

## Contributor Checklist:

* [ ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-live-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
It also requires setuptools for the docs environments, it seems

**Comment by sk1p** [comment]
> It also requires setuptools for the docs environments, it seems

Yeah, currently trying this locally. I wonder why, sphinxcontrib-bibtex actually already migrated away from `pkg_resources` already...

**Comment by sk1p** [comment]
> > It also requires setuptools for the docs environments, it seems
> 
> Yeah, currently trying this locally. I wonder why, sphinxcontrib-bibtex actually migrated away from `pkg_resources` already...

**Pull request merged**
