### PR TITLE
Remove dependency on bitshuffle package

### PR DESCRIPTION
**Pull request by sk1p**
Needs https://github.com/LiberTEM/LiberTEM-dectris-rs/pull/10

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

## Reviewer Checklist:

* [ ] `/azp run libertem.libertem-live-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
Probably the next step is releasing libertem-dectris-rs, making sure CI passes here, and then merging?

**Comment by sk1p** [comment]
Exactly. I'll take care of the release ASAP

**Pull request merged**
