### PR TITLE
DECTRIS support; use PipelinedExecutor for live processing

### PR DESCRIPTION
**Pull request by sk1p**
Support for DECTRIS detectors supporting the SIMPLON API, including support for the new `PipelinedExecutor`.

This also updates the Merlin support to use the new `PipelinedExecutor`.

## TODO

- [x] Update tests
- [x] Clean up merlin support (remove old thread pool etc.)
- [x] Add official example notebook for dectris
- [x] dectris sim doesn't seem to run on Py36, fix or skip
- [ ] request and add new `DEigerClient` copyright notice
- [x] Fix Py310 merlin tests - sim doesn't start?
- [x] Add user guide and reference documentation

## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-live-data` passed

### CODE REVIEW

**Comment by matbryan52** [comment]
> @matbryan52 pushed an example notebook into the prototypes folder in [407032d](https://github.com/LiberTEM/LiberTEM-live/pull/51/commits/407032df418205c7576bb01cb2ed84b38cbfb3aa)

Thanks! Finally had a moment to look at this and can confirm I got it running on a MIB dataset acquired here. Just had to increase the maximum open files limit as it's a one-file-per-frame type of dataset. I admit it also took me a while to figure out I needed to use the `--wait-trigger` argument on the simulator too (otherwise the reciever got a frame for the header bytes).

**Comment by sk1p** [comment]
> Thanks! Finally had a moment to look at this and can confirm I got it running on a MIB dataset acquired here. Just had to increase the maximum open files limit as it's a one-file-per-frame type of dataset. I admit it also took me a while to figure out I needed to use the `--wait-trigger` argument on the simulator too (otherwise the reciever got a frame for the header bytes).

Thank you for testing - yeah, in the other example notebooks, we had docs on this directly in the notebook, which I forgot to add to this one. Sorry about that, hope it didn't waste too much time. There is a question if we should change the defaults to something sensible - @uellue what do you think? I'm mostly starting the simulator with `--cached memfd --wait-trigger` these days...

FYI: the example notebook needs updates again, as I changed the `PipelinedExecutor` signature a bit for supporting CUDA etc.

**Comment by matbryan52** [comment]
> FYI: the example notebook needs updates again, as I changed the `PipelinedExecutor` signature a bit for supporting CUDA etc.

Yep, I just updated (I had to force update the branch bizarrely ?) and am letting decide its own spec. Still working. Am going to try to look more into the code this afternoon, around the meetings.

I haven't tried `--cached memfd` yet, will do this too.

**Comment by uellue** [comment]
> There is a question if we should change the defaults to something sensible - @uellue what do you think? I'm mostly starting the simulator with `--cached memfd --wait-trigger` these days...

Yes, sounds good to change the trigger default. Since we have the "experimental" disclaimer in the docs, we can probably just change it with a changelog notice. I usually don't cache and didn't notice much of a difference. Also, memfd is only supported on Linux. Maybe we can leave the default cache behavior as "no cache", or did you notice any misbehavior?

Regarding trigger, what about still accepting `--wait-trigger`, changing the default, and using sth. like `--wait-trigger=false` to get the previous default behavior?

**Comment by sk1p** [comment]
> Yes, sounds good to change the trigger default. Since we have the "experimental" disclaimer in the docs, we can probably just change it with a changelog notice. I usually don't cache and didn't notice much of a difference. Also, memfd is only supported on Linux. Maybe we can leave the default cache behavior as "no cache", or did you notice any misbehavior?

I don't really use the _non-cached_ case, so :shrug: I mostly built the `memfd` cached variant for benchmarking purposes - when I built it, it gave a lot better performance than the non-cached case, and was quite useful for "sniffing out" the bottlenecks in receiving, decoding, ... and good preparation work for supporting faster detectors in the future.

Directly comparing, without `--cached=memfd` I get about 1.1GiB/s, with cache I get 4.5GiB/s. 

> Regarding trigger, what about still accepting `--wait-trigger`, changing the default, and using sth. like `--wait-trigger=false` to get the previous default behavior?

Sounds good - means we don't have to update our notebooks, probably...

Let's do this in a separate PR.

**Comment by sk1p** [comment]
> Yep, I just updated (I had to force update the branch bizarrely ?) 

Sorry about that, that was me rebasing to current `upstream/master` to resolve conflicts and make the PR merge-able again.

> and am letting the executor decide its own spec. Still working. Am going to try to look more into the code this afternoon, around the meetings.

:+1:

> Is there anything in particular that I should focus on at this point?

For testing, mostly running different UDFs would be valuable - to sniff out any issues around serialization or scattering for example. Anything that is a bit more involved than the UDFs included with LiberTEM itself would be useful. Also, trying "edge cases" around error handling or startup/shutdown sequences.

One current limitation in the `PipelinedExecutor` is that  there no support for concurrently running multiple tasks, or running arbitrary functions while running a task, like the GUI would do.

As for code review, I think the most important parts are the new interfaces in `libertem.common.executor`, and how they are used by both the `PipelinedExecutor` and the merlin/dectris acquisition implementations. Feel free to ask any questions, ask for clarifications, and suggest alternatives - I think a lot of the code is also still missing docstrings, so if anything is unclear, please bug me to document it!

**Comment by matbryan52** [comment]
Understood, just for now I've started writing / implementing some test cases without looking too deeply at the code.

In fact I already found one issue where a UDF raising a bare `Exception` seems to hang the test suite (while normal derived exceptions seem to complete correctly (and `raise RuntimeError`)).

**Comment by uellue** [comment]
It seems we can tackle running the tests in CI as soon as LiberTEM 0.10 is developed?

**Comment by uellue** [comment]
Perhaps we should make Dectris support an extra so that we don't have a hard dependency on Bitshuffle? It just made installation on the Merlin PC harder and we really don't need it on that system.

**Comment by sk1p** [comment]
> Perhaps we should make Dectris support an extra so that we don't have a hard dependency on Bitshuffle? It just made installation on the Merlin PC harder and we really don't need it on that system.

Done - `bitshuffle` and `lz4` are now optional.

**Comment by sk1p** [comment]
Requires https://github.com/LiberTEM/LiberTEM/pull/1316 to run reliably after going into error states (i.e. `test_frame_skip`).

**Comment by sk1p** [comment]
azp run libertem.libertem-live-data

**Comment by sk1p** [comment]
> * [ ]  request and add new `DEigerClient` copyright notice

From my perspective, this is the major item still blocking the PR - we could also handle this as a separate issue, but at least before the release the copyright header should be fixed.

Notes on the code coverage: 

- `DEigerClient` is obviously not fully tested/covered here
- missing tests for correction data usage (not sure if this is included in our data dump?)
- little coverage in the DECTRIS sim - mostly: the Python sender, and alternative triggering mechanisms
- same in the `DectrisAcquisition` - tests missing for `exts`/`ints` triggering, corrections, some boundary cases
- new `MerlinCommHandler`: missing some edge cases

Further efficiency improvements are definitely possible, but IMHO can and should be done once this is merged (also important to unblock #56)

**Review by uellue — APPROVED** [review]
Looks good to me! 🏆

**Comment by uellue** [comment]
Merging!

**Pull request merged**
