### PR TITLE
Fix tiling scheme so that `process_partition()` works

### PR DESCRIPTION
**Pull request by uellue**
## Contributor Checklist:

* [x] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

## Reviewer Checklist:

* [x] `/azp run libertem.libertem-live-data` passed

### CODE REVIEW

**Comment by uellue** [comment]
Not sure if we want to go with the whole change management process here?

**Comment by sk1p** [comment]
> Not sure if we want to go with the whole change management process here?

Actually it would be great to have a test case for a `process_partition` - to at least have a regression test for this issue.

**Pull request merged**
